### ISSUE TITLE
pressure time intergrals

### ISSUE THREAD

**Issue by eleonora-mont** [GallVp/footPress#1]
Hello,

I was wondering if you added functions to calculate pressure time integrals out of peak pressure matrices in matlab files instead of frames. 

Thanks,
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

I am not sure I fully understand your question. Can you please elaborate with an example?

**Comment by eleonora-mont** [comment]
Hi Usman,

Sorry for the vague question. I am working with maximum pressure picture on matlab and I am looking for dependency between pressure metrics (e.g. peak pressure and pressure time integral). However, I am not understanding how to calculate pressure time integral values out of the maximum pressure picture matrices. The software I am using does not export whole matrix of pressure time integral values but only values within the regions selected (e.g. PTI values for heel or hallux). I see from the codes you provide that calculation of CoP and CoP trajectory is possible so I was wondering if you perhaps created also codes to calculate other pressure metrics. I appreciate that your code is for frames of pressure rather than maximum pressure pictures but I thought that it was worth trying and ask you this. I hope I explained my issue clearer. 

Thanks,
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

I did not create separate functions for computing pressure time integral. Pressure time integral code is embedded inside the `plotter/plotFootData` function at line [933 - 938](https://github.com/GallVp/footPress/blob/5e6d93c8a61f4f85793ac0a7daeb8fa0541734bb/Plotters/plotFootData.m#L933).

However, creating a separate function from the embedded code should be straightforward. Here is an example code:

```MATLAB
function ptiFrame = computePtiFrame( inputFrames, frameRate)
% computePtiFrame Computes pressure time integral by numerically integrating 
% pressure across time.
% inputFrames is a 3D matrix with sensel values across rows and columns,
% and frames across the third dimension. ptiFrame is a 2D matrix with pti value
% for each sensel  across rows and columns.

sampleTime = 1 / frameRate;

ptiFrame = sum(inputFrames, 3) .* sampleTime;

end
```

In your case, you don't have values from individual sensels. Rather, you have peak pressure values for regions which were computed from sensels in those regions. Let's say you have three regions: Upper, middle, lower. To compute PTI you need a time dimension so we'll assume you have values for these regions at multiple consecutive time points. You can arrange this data in a 2D matrix, with first dimension for regions and the second dimension for time. In this case, the pit can be computed as follows:

```MATLAB
function ptiOfRegions = computePtiOfRegions( regionFrames, frameRate)

sampleTime = 1 / frameRate;

ptiOfRegions = sum(regionFrames, 2) .* sampleTime;

end
```
Example: There are three regions with peak pressure at 6 time points. frameRate is 100 samples/sec. The result is pit for each region.

```MATLAB
>> regionFrames = [1 2 3 0 0 0;4 5 6 1 2 3;9 9 9 9 9 9]

regionFrames =

     1     2     3     0     0     0
     4     5     6     1     2     3
     9     9     9     9     9     9

ptiOfRegions = computePtiOfRegions( regionFrames, frameRate)

    0.0600
    0.2100
    0.5400
```
I hope this answers your question.

**Comment by eleonora-mont** [comment]
Hi Usman, 

Thanks for your reply. It does answer my question, however, I haven't specified that I am not working with regions of interest but I am conducting continuous analysis so I consider the foot matrix as a whole instead of the regions (attached example). I attached an example matrix where each row is a single step and columns represent peak pressure value for each pixel. Would I be able to adapt the code you just sent me to this matrix? 

Thanks a lot,
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

I don’t see an attachment. How can I access your attached example?

**Comment by eleonora-mont** [comment]
Hi Usman,


It probably didn't go through on GitHub. These are the examples, I attached them both in mat file format and excel. Hope you can get access to it.


Thanks,
Eleonora

________________________________

**Comment by GallVp** [comment]
No, I still can’t access it. Perhaps you can send me a dropbox link?

**Comment by eleonora-mont** [comment]
[data_example.xlsx](https://github.com/GallVp/footPress/files/6042148/data_example.xlsx)

Hi Usman, 
I think I managed now to attach the data example. It is in excel format though but it's copied and paste from the original mat file. Pressure values for the single steps (rows) are indexed to the number of pixels present in the template (columns, n=221).
Thanks,
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

I have got the data now. For pressure time integral (PTI) we need to have a time dimension in out data. Our current dimensions are steps and pressure pixels. We can integrate across steps if we know the sample time which is the time taken by the sensor system to take a measurement during a step. Let's say your sample time is 1/50 seconds, then the following code gives you the pressure time integral across steps:

```MATLAB
% Data dimensions
>> size(dataexample)

ans =

    36   221

>> dt = 1/50; % Sample time

>> pti = sum(dataexample).*dt;

% Result dimensions
>> size(pti)

ans =

     1   221
```

In the result variable we have PTI value for each pressure pixel.

**Comment by eleonora-mont** [comment]
Hi Usman,

Thanks so much for this. Last question, I promise. My pressure system collected data at 100Hz. Would it be right to consider my time dimension as 1/100 seconds?

**Comment by GallVp** [comment]
You are welcome. Yes, I agree that the sample time is 1/100 seconds.

**Comment by eleonora-mont** [comment]
Thanks so much for your precious help, I just tried everything and it works just fine!
