### ISSUE TITLE
computeCOPtrajectory

### ISSUE THREAD

**Issue by eleonora-mont** [GallVp/footPress#2]
Hello @GallVp 

I am using your function computeCOPtrajectory to determine the trajectory of the CoP out of raw pressure frames. I was wondering, is the trajectory exported in the measurement unit of the sensors or in other units (e.g. mm)? 

Thanks,
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

It computes the trajectory in `sensel` coordinates (x, y). Let's say you have an array of 500 x 500 `sensels` in your device and each `sensel` has a width of 2mm and height of 2mm. Then, a COP trajectory location at x:15, y:105 in `sensel` units corresponds to x:29 (14x2mm + 1mm), y:209 (104x2mm + 1mm) in mm. For this calculation we are using the centre of a `sensel` as the trajectory point. The reference point (top left or bottom left) depends on the sensor system you are using and it's usually specified in the data-sheet.

**Comment by eleonora-mont** [comment]
Hi @GallVp 

Sorry for the late reply and thanks for your clarifications. So, if I was to calculate the velocity of the cop trajectory (let's say the anterior posterior trajectory(x)), my unit measurement will be in sensel unit/Hz if I do not convert the trajectories. Ideally, I would like to have the cop velocity (x) in milliseconds but I am struggling to find a way to do it. Would you say that it is best to convert the trajectories in mm as first step, and then calculate the velocity of the cop? 

Thanks again!
Eleonora

**Comment by GallVp** [comment]
Hi @eleonora-mont 

Let's say your AP trajectory is a MATLAB vector in sensel units; apTraj= [35, 45, 44, 47, 54, 60, 66, 70, 71, ...];
Your sample rate is 100 Hz which means the sample time is 1/00; deltaT = 0.01 seconds.

AP velocity (sensel/second) = diff(apTraj) ./ deltaT 

This velocity can be converted to sensel per millisecond by multiplying it to 1/1000. To convert the result to millimetre/ms, we need the device least count expressed in millimetre per sensel. Let's assume it is 2mm/sensel. All together:

AP velocity (mm/ms) = (diff(apTraj) ./ deltaT) .x (1/100) .x (2)

**Comment by eleonora-mont** [comment]
Hi @GallVp ,

Yes my script stopped after calculating the AP_velocity in sensel/second. Can I ask what do you mean by device least count? Is it the specification of each sensel measurement? Because the only thing I know about the sensors I used, is that there are 4 sensors per cm2, therefore one sensor is 0.5 cm in length and width. 

Thanks,
Eleonora

**Comment by GallVp** [comment]
@eleonora-mont 

Yes, that's what I meant by least count. 0.5 cm per sensel.

**Comment by eleonora-mont** [comment]
Thank you so much for your help!
