### ISSUE TITLE
exampleL.asf

### ISSUE THREAD

**Issue by cLood4io** [GallVp/footPress#4]
I COULDNT FIND THE EXAMPLE OF DATA TO TEST IT CAN YOU PLZ PROVIDE ME WITH ONE...THANK U FOR YOUR EFFORT

**Comment by GallVp** [comment]
Hi @cLood4io 

I can email the example files to you. Please share your email ID.

Cheers

**Comment by GallVp** [comment]
I have also added the sample files under `Example Data` folder.
